import { EmptyAnalysis, formatNumber, manwon, pct, resourceLabel, StepHeading } from "./common";
import type { ReviewStepProps } from "./types";
import { summarizeDemand } from "../../application/scenarioAnalysis";

export function ReviewStep({ candidate, layout, market, operation, financial, comparison, sensitivity, stale, onExport }: ReviewStepProps) {
  const evaluation = operation?.ok ? operation : null;
  const metrics = evaluation?.aggregate.metrics;
  const expected = evaluation ? summarizeDemand(evaluation.resolved) : null;
  const source = evaluation?.resolved.configuration.market;
  const dayType = evaluation?.resolved.configuration.simulation?.dayType;
  const traffic = source?.buckets.filter(bucket => bucket.dayType === dayType && bucket.footTrafficPersons !== null) ?? [];
  const peak = traffic.reduce<(typeof traffic)[number] | null>((best, bucket) => !best || (bucket.footTrafficPersons ?? -1) > (best.footTrafficPersons ?? -1) ? bucket : best, null);
  const successful = comparison?.rows.filter(row => row.evaluation.ok) ?? [];
  const financials = successful.flatMap(row => row.evaluation.ok && row.evaluation.financial ? [row.evaluation.financial] : []);
  const attention: string[] = [];
  if (market?.provenance.kind === "demo") attention.push("상권은 Demo 자료입니다. 실제 후보지의 유동인구와 경쟁점 자료로 바꾸기 전에는 지역 수요를 판단할 수 없습니다.");
  if (metrics && metrics.customersLost.mean > 0) attention.push(`평균 ${formatNumber(metrics.customersLost.mean)}명의 홀 고객이 관측 중 이탈했습니다. 대기 한도와 인력·테이블·주방 조건을 함께 검토하세요.`);
  if (metrics && metrics.customersUnfinished.mean > 0) attention.push(`관측 종료 시 평균 ${formatNumber(metrics.customersUnfinished.mean)}명의 홀 고객이 미완료 상태입니다. 완료 고객만 매출에 반영했습니다.`);
  if (financial && financial.monthlyOperatingProfit < 0) attention.push(`현재 조건의 월 영업이익은 ${manwon(financial.monthlyOperatingProfit)}입니다. 완료량과 객단가·비용 가정을 함께 확인해야 합니다.`);
  if (financial?.observedThroughputMarginPerDay !== null && financial?.observedThroughputMarginPerDay !== undefined && financial.observedThroughputMarginPerDay < 0) attention.push("이번 관측 처리량은 손익분기 영업량보다 적습니다. 이는 최대 처리 용량을 검증한 결과가 아닙니다.");
  if (layout?.assumptions.some(item => item.id === "scenario-capacity-intervention")) attention.push("현재 정원은 가상 용량 개입입니다. 통로·테이블 간격·배치 가능성은 공간설계에서 별도로 검토해야 합니다.");
  const sensitivityPoints = sensitivity?.results.filter(point => point.evaluation.ok) ?? [];
  const revenues = sensitivityPoints.flatMap(point => point.evaluation.ok && point.evaluation.financial ? [point.evaluation.financial.monthlyRevenue] : []);
  const served = sensitivityPoints.flatMap(point => point.evaluation.ok ? [point.evaluation.aggregate.metrics.customersServed.mean] : []);
  const blockers = evaluation?.aggregate.bottlenecks.filter(item => item.replicationCount > 0).slice(0, 3) ?? [];
  return <div className="analysis-page analysis-review"><StepHeading number="08" title="판단에 필요한 근거를 한곳에." description="공간, 수요, 운영과 비용을 연결한 이번 검토의 요약입니다." action={onExport && <button className="analysis-button analysis-button-secondary" onClick={onExport} disabled={stale || !evaluation || !financial || !comparison?.ok}>검토 결과 저장</button>} />
    {stale && <p className="analysis-notice analysis-notice-warning" role="status">조건이 바뀐 뒤 다시 계산하지 않은 결과가 있습니다. 가상영업·시나리오·수익성을 갱신한 후 검토 결과를 저장하세요.</p>}
    {evaluation && (!financial || !comparison?.ok) && <p className="analysis-note">시나리오 비교와 수익성 계산을 모두 완료하면 검토 결과를 저장할 수 있습니다.</p>}
    <section className="analysis-review-site"><div><span className="analysis-eyebrow">CANDIDATE SITE</span><h2>{candidate.projectName || "후보 점포"}</h2><p>{candidate.brandName || "브랜드 미입력"} · {candidate.address || "주소 미입력"}</p></div><dl><div><dt>면적</dt><dd>{formatNumber(layout?.totalAreaM2 ?? candidate.knownAreaM2)} m²</dd></div><div><dt>확정 운영 정원</dt><dd>{formatNumber(layout?.confirmedCapacity, 0)}석</dd></div><div><dt>테이블</dt><dd>{formatNumber(layout?.tableCount, 0)}개</dd></div></dl></section>
    {expected && <section className="analysis-section"><div className="analysis-section-heading"><div><h2>상권 자료에서 매장 수요까지</h2><p>{source?.provenance.kind === "demo" ? "실측이 아닌 예시 상권에 방문 가정을 적용했습니다." : "실행 당시 상권 자료와 방문 가정을 기준으로 합니다."}</p></div></div>
      {peak && <p className="analysis-note">선택 요일의 상권 유동인구가 가장 큰 시간은 {peak.hour}시, {formatNumber(peak.footTrafficPersons)} 통행 명/시간입니다. 매장 방문 고객 수와 구분합니다.</p>}
      <dl className="analysis-review-facts"><div><dt>가정에 따른 홀 유입</dt><dd>{formatNumber(expected.expectedDineInCustomers)}명</dd></div><div><dt>가정에 따른 배달 주문</dt><dd>{formatNumber(expected.expectedDeliveryOrders)}건</dd></div></dl>
      <p className="analysis-note">관측 구간과 실제 입장 허용 시간이 겹치는 동안의 기대 유입량입니다. 반복실험의 실제 도착 수와 처리 완료량은 이 값과 다를 수 있습니다.</p>
    </section>}
    {!evaluation ? <EmptyAnalysis title="가상영업을 실행하면 검토 근거가 모입니다.">후보지 → 공간설계 → 상권 → 수요를 준비하고 가상영업을 실행하세요. 이후 시나리오와 수익성에서 조건을 비교할 수 있습니다.</EmptyAnalysis> : <>
      <section className="analysis-section"><div className="analysis-section-heading"><div><h2>이 가정으로 운영했습니다.</h2><p>{evaluation.replication.count}회 반복 · {formatNumber(evaluation.resolved.configuration.simulation!.durationSeconds / 3600)}시간 관측</p></div>{market?.provenance.kind === "demo" && <span className="analysis-tag analysis-tag-demo">DEMO 기반</span>}</div><dl className="analysis-review-facts"><div><dt>업종 참여율</dt><dd>{pct(evaluation.resolved.configuration.demandParameters!.categoryParticipationRate)}</dd></div><div><dt>점포 선택 비율</dt><dd>{pct(evaluation.resolved.configuration.demandParameters!.brandShare)}</dd></div><div><dt>방문 전환율</dt><dd>{pct(evaluation.resolved.configuration.demandParameters!.visitConversionRate, 2)}</dd></div><div><dt>조리 인력 / 동시 조리</dt><dd>{evaluation.resolved.configuration.operation!.resources.cooks}명 / {evaluation.resolved.configuration.operation!.resources.kitchenConcurrentOrders}건</dd></div></dl></section>
      <section className="analysis-section"><div className="analysis-section-heading"><div><h2>관측된 운영 결과</h2><p>반복실험 평균과 최솟값–최댓값입니다.</p></div></div><div className="analysis-review-outcome"><div><span>홀 처리 완료 / 관측 구간</span><strong>{formatNumber(metrics!.customersServed.mean)}명</strong><small>{formatNumber(metrics!.customersServed.min)}–{formatNumber(metrics!.customersServed.max)}명</small></div><div><span>평균 대기</span><strong>{formatNumber(metrics!.averageWaitingSeconds.mean / 60)}분</strong><small>종료 시 미완료 대기 포함</small></div><div><span>주방 가동률</span><strong>{pct(metrics!.kitchenUtilization.mean)}</strong><small>전체 관측 시간 기준</small></div></div>
        <p className="analysis-observation">{blockers.length ? `반복 실행에서 자원 대기가 기록된 곳: ${blockers.map(item => `${resourceLabel(item.resource)} (${item.replicationCount}/${evaluation.replication.count}회)`).join(" · ")}.` : "이번 실행에서는 자원 부족으로 인한 대기가 기록되지 않았습니다."}</p><p className="analysis-note">대기 발생 빈도는 증설 효과의 순위가 아닙니다. 원인을 확인하려면 해당 자원을 바꾸어 비교하세요.</p>
      </section>
      <section className="analysis-section"><div className="analysis-section-heading"><div><h2>수익구조와 조건별 차이</h2><p>완료 처리량에 가격·영업일·비용 가정을 적용했습니다.</p></div></div>{!financial ? <p className="analysis-note">수익성 단계에서 비용 가정을 입력하고 계산하세요.</p> : <><table className="analysis-table"><tbody><tr><th scope="row">기준 조건의 월 매출</th><td>{manwon(financial.monthlyRevenue)}</td></tr><tr><th scope="row">기준 조건의 월 영업이익</th><td className={financial.monthlyOperatingProfit < 0 ? "analysis-negative" : ""}>{manwon(financial.monthlyOperatingProfit)}</td></tr><tr><th scope="row">손익분기 월 매출</th><td>{manwon(financial.breakEvenRevenue)}</td></tr><tr><th scope="row">손익분기 홀 고객 / 배달 주문</th><td>{formatNumber(financial.breakEvenDailyDineInCustomers)}명 / {formatNumber(financial.breakEvenDailyDeliveryOrders)}건 · 영업일당</td></tr><tr><th scope="row">단순 투자 회수기간</th><td>{financial.estimatedPaybackMonths === null ? "계산 불가 · 월 영업이익 0 이하" : `${formatNumber(financial.estimatedPaybackMonths)}개월`}</td></tr></tbody></table>{financials.length > 1 && <p className="analysis-observation">비교한 {financials.length}개 시나리오의 월 매출은 {manwon(Math.min(...financials.map(item => item.monthlyRevenue)))}–{manwon(Math.max(...financials.map(item => item.monthlyRevenue)))}, 영업이익은 {manwon(Math.min(...financials.map(item => item.monthlyOperatingProfit)))}–{manwon(Math.max(...financials.map(item => item.monthlyOperatingProfit)))}입니다.</p>}<p className="analysis-note">이 범위는 설정한 시나리오 사이의 차이이며 예측 신뢰구간이 아닙니다.</p></>}</section>
      <section className="analysis-section"><div className="analysis-section-heading"><div><h2>어떤 조건을 바꾸어 보았나요?</h2></div></div>{!sensitivity ? <p className="analysis-note">시나리오 단계에서 방문 전환율·좌석·주방·객단가 중 하나를 바꾸어 비교하세요.</p> : <p className="analysis-observation">{sensitivity.parameter.label}을 {sensitivity.results.length}개 조건으로 비교했습니다. {served.length > 0 && `홀 처리 완료 평균은 ${formatNumber(Math.min(...served))}–${formatNumber(Math.max(...served))}명/관측 구간입니다. `}{revenues.length > 0 && `해당 조건의 월 매출은 ${manwon(Math.min(...revenues))}–${manwon(Math.max(...revenues))}입니다.`}</p>}</section>
      <section className="analysis-section"><div className="analysis-section-heading"><div><h2>계약 전에 확인할 사항</h2><p>이번 입력과 계산 결과에서 확인된 항목입니다.</p></div></div>{attention.length ? <ol className="analysis-attention-list">{attention.map((item, index) => <li key={index}><span>{String(index + 1).padStart(2, "0")}</span><p>{item}</p></li>)}</ol> : <p className="analysis-note">추가로 드러난 계산상 주의 항목은 없습니다. 입력한 수요·비용·운영 가정을 실제 자료와 대조하세요.</p>}</section>
    </>}
    {candidate.notes && <section className="analysis-section"><h2>담당자 검토 메모</h2><p className="analysis-review-notes">{candidate.notes}</p></section>}
    <p className="analysis-review-footer">이 요약은 출점 점수나 자동 승인 판단을 제공하지 않습니다. 입력 자료와 가정을 확인한 담당자가 검토 근거로 사용합니다.</p>
  </div>;
}
